mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#服务器端口
server:
  port: 1086

#数据源配置
spring:
 datasource:
   url: jdbc:mysql://172.17.0.2:3306/boot
   username: root
   password: root